name: Build Windows x86

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch: # Permite rodar manualmente

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust (i686 target)
      run: |
        rustup toolchain install stable-i686-pc-windows-msvc
        rustup default stable-i686-pc-windows-msvc

    - name: Build Project
      run: cargo build --release --target i686-pc-windows-msvc

    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: mouseplay-windows-x86
        path: target/i686-pc-windows-msvc/release/mouseplay.exe
